### ISSUE TITLE
Batchify geocross loss

### ISSUE THREAD

**Issue by giannisdaras** [giannisdaras/ilo#1]

**Comment by btroussel** [comment]
Hi, thank you very much for your work and for letting it open source for the research area ! 

I'm currently working on your project, and I don't understand how the loss_geocross is made. It doesn't seem to work on batches (which is I suppose the goal of this issue). But more importantly, I don't understand the meaning of the factor "2" in the call loss_geocross(self.latent_z[2 * start_layer:]).

Thank you in advance for your help !
